### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by TheAquabat** [aunetx/deezer-linux#75]
I am getting this error on both the flatpak and the deb package. It happens when I click on the "open deezer" link of the browser... So I cant login because then it crashes

```
TypeError: Cannot read property '1' of null
    at DeepLinkService.handleAutolog (/app/main/resources/app.asar/build/main.js:1060:53)
    at DeepLinkService.handlePath (/app/main/resources/app.asar/build/main.js:1040:16)
    at App.<anonymous> (/app/main/resources/app.asar/build/main.js:2874:31)
    at App.emit (events.js:315:20)
    at App.EventEmitter.emit (domain.js:467:12)

```

**Comment by leandroembu** [comment]
Same issue here.

**Comment by TheAquabat** [comment]
unfortunately, the AppImage also doesnt work.

**Comment by Meincrakker** [comment]
It does work perfectly on my end. Can you explain what you did?

You need to press "move to app menu" in gearlever and select the correct deezer app when coming back from the browser or just uninstall the other deezer installs.

**Comment by TheAquabat** [comment]
The AppImage does work, but the problem is the same as before, you cant login, though this one doesnt crash tho.

**Comment by Meincrakker** [comment]
No. I deleted everything in /home/.../.config/deezer-desktop and the Appimage was able to log me in again. Maybe deleting it helps :shrug: 

I think the flatpak repo has an older version (6.0.110) of deezer that should work (it works at least for me). Or you can get an even older version of Deezer that is known to work as described [here](https://itsfoss.com/downgrade-flatpak-packages/).
